# This is a basic workflow to help you get started with Actions

name: docker-compose setup

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

        run: |
          mkdir -p ~/data/database/
	        mkdir -p ~/data/pgadmin/

      - name: docker-compose build
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: check running
        run: |
          docker ps --format "{{.State}}" --filter name=backend | grep running
          docker ps --format "{{.State}}" --filter name=frontend | grep running
          docker ps --format "{{.State}}" --filter name=database | grep running
          docker ps --format "{{.State}}" --filter name=pgadmin | grep running

      - name: docker-compose down
        run: docker-compose down
